name: StrideApp
options:
  bundleIdPrefix: com.stride
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  StrideApp:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utilities
      - path: Assets.xcassets
        buildPhase: resources
      - path: Fonts
        buildPhase: resources
      - path: LaunchScreen.storyboard
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: StrideApp.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.stride.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleDisplayName: Stride
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.healthcare-fitness
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
